apiVersion: v1
kind: Pod
metadata:
  name: cluster-ip-pod
  labels:
    app.kubernetes.io/name: proxy
    environment: dev
    app: frontend
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
      - containerPort: 80
        name: http-web-svc
      resources:
        - limits:
            cpu: 3
            memory: 200
        - requests:
            cpu: 2
            memory: 150
---
apiVersion: v1
kind: Service
metadata: 
  name: service-conf
spec:
  selector:
    app.kubernetes.io/name: proxy
    environment: dev
    app: frontend
  ports:
  - name: service-port1
    protocol: TCP
    port: 80
    targetPort: http-web-svc