apiVersion: apps/V1
kind: Deployment
metadata:
  name: Nginx-Pod
  labels:
    env: dev
spec:
  selector:
    matchlabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    containers:
      - name: nginx
        image: nginx-2024
        ports:
          - conatinerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 150m
            memory: 150Mi
        livenessProbe:
          httpGet:
            port: 80
            path: /healthz
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 
          periodSeconds: 
        readinessProbe:

