---
apiVersion: apps/v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  DB_USER: HARI
  DB_PASS: VARDHAN

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  labels:
    env: test
    app: myapp1
spec:
  serviceName: "my-app-pod"
  replicas: 3
  selector:
    matchLabels:
        env: test
        app: myapp1
  template:
    metadata:
      name: myapp1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 800m
              memory: 1Gi
            requests:
              cpu: 600m
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 40
            timeoutSecoonds: 2
            failureThreashold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 40
            timeoutSecoonds: 2
            failureThreashold: 3
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-password
                  key: DB_PASS
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
          - name: csi-volume-inline
            mountPath: "/data"
          command: ["sleep", "10000"]
      volumes:
        - name: csi-volume-inline
          csi:
            driver: inline-storage-class
            volumeAttributes:
              foo: bar
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
           

