docker_setup_and_ecr_push:
  prerequisites:
    - sudo yum install -y yum-utils
    - sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - sudo yum install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
    - sudo usermod -aG centos docker
    - sudo systemctl start docker
    - sudo docker run hello-world

  aws_ecr_public_login:
    - command: >
        aws ecr-public get-login-password --region us-east-1 |
        docker login --username AWS --password-stdin public.ecr.aws/p0u5t5q2

  docker_image_operations:
    - build:
        - command: docker build -t haridevops .
    - tag:
        - command: docker tag haridevops:latest public.ecr.aws/p0u5t5q2/haridevops:latest
    - push:
        - command: docker push public.ecr.aws/p0u5t5q2/haridevops:latest

  optional_custom_image_tag:
    - build_with_custom_tag:
        - template: docker build -t public.ecr.aws/p0u5t5q2/haridevops:<Image-Name> .
